const heroBaseKit = {
  mage: {
    power: {
      name: "Fireball",
      manaCost: 2,
      description: "Deal 2 damage",
      damageValue: 2,
    },

    deck: [
      {
        name: "Arcane Missile",
        manaCost: 1,
        description: "Deal 1 damage.",
        damageValue: 1,
      },
      {
        name: "Mana Sprite",
        manaCost: 1,
        description: "A weak magical creature.",
        attack: 1,
        health: 2,
      },
      {
        name: "Frost Bolt",
        manaCost: 2,
        description: "Deal 3 damage.",
        damageValue: 3,
      },
      {
        name: "Apprentice Mage",
        manaCost: 2,
        description: "A student of the arcane arts.",
        attack: 2,
        health: 3,
      },
      {
        name: "Flame Burst",
        manaCost: 3,
        description: "Deal 4 damage.",
        damageValue: 4,
      },
      {
        name: "Arcane Scholar",
        manaCost: 3,
        description: "A knowledgeable spellcaster.",
        attack: 3,
        health: 4,
      },
      {
        name: "Ice Barrier",
        manaCost: 3,
        description: "Restore 4 health.",
        healValue: 4,
      },
      {
        name: "Fire Elemental",
        manaCost: 4,
        description: "A blazing elemental warrior.",
        attack: 4,
        health: 5,
      },
      {
        name: "Blizzard",
        manaCost: 4,
        description: "Deal 2 damage to all enemies.",
        damageValue: 2,
      },
      {
        name: "Arcane Golem",
        manaCost: 5,
        description: "A heavy magical construct.",
        attack: 5,
        health: 6,
      },
      {
        name: "Meteor Strike",
        manaCost: 5,
        description: "Deal 6 damage.",
        damageValue: 6,
      },
      {
        name: "Crystal Dragon",
        manaCost: 6,
        description: "A powerful magical dragon.",
        attack: 6,
        health: 7,
      },
      {
        name: "Phoenix Flame",
        manaCost: 7,
        description: "Deal 8 damage.",
        damageValue: 8,
      },
      {
        name: "Archmage Valen",
        manaCost: 8,
        description: "Master of forbidden magic.",
        attack: 8,
        health: 8,
      },
      {
        name: "Celestial Inferno",
        manaCost: 10,
        description: "Deal 12 damage.",
        damageValue: 12,
      },
    ],
  },
};